"use client";

import { useState, useEffect } from "react";
import { RefreshCw, Copy, Share2 } from "lucide-react";
import { AnimatedGradient } from "@/components/AnimatedGradient";
import { toast } from "@/components/Toast";

type Props = {
  initialReason: string;
};

export function NoServiceContainer({ initialReason }: Props) {
  const [reason, setReason] = useState(initialReason);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shareUrl, setShareUrl] = useState("");

  useEffect(() => {
    setShareUrl(window.location.origin + "/no");
  }, []);

  const fetchNewReason = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/no", { method: "GET" });
      if (!res.ok) throw new Error("Failed to fetch");
      const data = await res.json();
      setReason(data.reason);
      setCopied(false);
    } catch (err) {
      console.error(err);
      toast.info("Failed to generate from server. Trying locally...");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(reason);
      setCopied(true);
      toast.success("Copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.info("Failed to copy. Please copy manually.");
    }
  };

  const twitterShareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
    `"${reason}" — Refusal generated by No-as-a-Service on Trendly`
  )}&url=${encodeURIComponent(shareUrl)}`;

  const whatsappShareUrl = `https://wa.me/?text=${encodeURIComponent(
    `"${reason}" — Generated by No-as-a-Service on Trendly: ${shareUrl}`
  )}`;

  const linkedinShareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(
    shareUrl
  )}`;

  return (
    <div className="w-full max-w-2xl relative">
      <AnimatedGradient />

      <div className="w-full rounded-2xl border border-border/40 bg-background/60 backdrop-blur-xl p-8 md:p-12 shadow-2xl animate-fade-up relative z-10 flex flex-col items-center text-center">
        {/* Badge */}
        <span className="cat-badge mb-6">No-as-a-Service</span>

        {/* Title */}
        <h1 className="font-serif text-3xl font-bold tracking-tight text-foreground sm:text-4xl mb-4">
          Say No, <span className="text-primary">Without the Guilt</span>
        </h1>
        <p className="text-muted-foreground text-sm max-w-md mb-8">
          Need to decline a meeting, project, or invitation? Let our generator craft the perfect refusal reason.
        </p>

        {/* Excuse Box */}
        <div className="w-full min-h-[160px] flex items-center justify-center border border-border/40 bg-secondary/30 rounded-2xl p-6 md:p-8 mb-8 relative group overflow-hidden">
          <div className="absolute top-4 left-4 text-primary/20 text-6xl font-serif pointer-events-none select-none">
            “
          </div>
          <div className="absolute bottom-0 right-4 text-primary/20 text-6xl font-serif pointer-events-none select-none translate-y-4">
            ”
          </div>
          <p className={`font-serif text-lg md:text-xl text-foreground leading-relaxed transition-all duration-300 ${loading ? 'opacity-30 blur-[2px] scale-[0.98]' : 'opacity-100 scale-100'}`}>
            {reason}
          </p>
        </div>

        {/* Main Controls */}
        <div className="flex flex-col sm:flex-row gap-4 w-full justify-center mb-10">
          <button
            onClick={fetchNewReason}
            disabled={loading}
            className="btn btn-primary h-12 px-6 flex items-center justify-center gap-2 relative active:scale-95 transition-transform group"
          >
            <RefreshCw className={`w-4 h-4 transition-transform duration-500 ${loading ? 'animate-spin' : 'group-hover:rotate-180'}`} />
            {loading ? "Generating..." : "Generate Another"}
          </button>
          
          <button
            onClick={copyToClipboard}
            className="btn btn-secondary h-12 px-6 flex items-center justify-center gap-2 active:scale-95 transition-transform"
          >
            <Copy className="w-4 h-4" />
            {copied ? "Copied!" : "Copy to Clipboard"}
          </button>
        </div>

        {/* Social Share Section */}
        <div className="w-full border-t border-border/30 pt-6 flex flex-col items-center gap-4">
          <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
            <Share2 className="w-3.5 h-3.5" /> Share this refusal
          </span>
          <div className="flex flex-wrap justify-center gap-3">
            <a
              href={twitterShareUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-background/50 hover:bg-black hover:text-white hover:border-black px-4 py-2 text-xs font-semibold text-muted-foreground transition-all"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.73-8.835L1.254 2.25H8.08l4.253 5.622zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
              </svg>
              Share on X
            </a>
            <a
              href={linkedinShareUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-background/50 hover:bg-[#0077b5] hover:text-white hover:border-[#0077b5] px-4 py-2 text-xs font-semibold text-muted-foreground transition-all"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
              </svg>
              LinkedIn
            </a>
            <a
              href={whatsappShareUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-background/50 hover:bg-[#25d366] hover:text-white hover:border-[#25d366] px-4 py-2 text-xs font-semibold text-muted-foreground transition-all"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
              </svg>
              WhatsApp
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
